In [17]:
import os

import numpy as np
import matplotlib.pyplot as plt

from mazemdp.maze import build_maze, create_random_maze
from random import seed
from mazemdp import create_random_maze
from replay_sim import Agent
from utils import evaluate, to_plot, Replay, SimuData

from arguments import get_args, get_args_string
import argparse
from IPython.display import display, clear_output

In [18]:
parser = argparse.ArgumentParser()
parser.add_argument("--pre_explore", type = bool, default = True)
parser.add_argument("--start_random", type = bool, default = False)
parser.add_argument("--transi_goal_to_start", type = bool, default = True)

parser.add_argument("--plan_policy", type = str, default = "softmax")
parser.add_argument("--plan_only_start_end", type = bool, default = True)
parser.add_argument("--planning_steps", type = int, default = 20)
parser.add_argument("--expand_further", type = bool, default = True)

parser.add_argument("--set_all_need_to_1", type = bool, default = False)
parser.add_argument("--set_all_gain_to_1", type = bool, default = False)
parser.add_argument("--baseline_gain", type = float, default = 1e-10)
parser.add_argument("--EVM_thresh", type = float, default = 0)

parser.add_argument("--allow_loops", type = bool, default = False)
parser.add_argument("--online_offline", type = str, default = "online")
parser.add_argument("--remove_samestate", type = bool, default = True)


parser.add_argument("--gamma", type = float, default = 0.9)
parser.add_argument("--alpha", type = float, default = 1)
parser.add_argument("--lambda_", type = float, default = 0)
parser.add_argument("--T_learning_rate", type = float, default = 0.9)

parser.add_argument("--action_policy", type = str, default = "softmax")
parser.add_argument("--epsilon", type = float, default = 0.05)
parser.add_argument("--tau", type = float, default = 0.2)

parser.add_argument("--simulations", type = int, default = 50)
parser.add_argument("--episodes", type = int, default = 50)
parser.add_argument("--max_episode_steps", type = int, default = 1e5)

_StoreAction(option_strings=['--max_episode_steps'], dest='max_episode_steps', nargs=None, const=None, default=100000.0, type=<class 'int'>, choices=None, help=None, metavar=None)

In [19]:
args = parser.parse_args("") # trick for argparse on note book
all_default = {}
for key in vars(args):
    all_default[key] = parser.get_default(key)
print(all_default)

{'pre_explore': True, 'start_random': False, 'transi_goal_to_start': True, 'plan_policy': 'softmax', 'plan_only_start_end': True, 'planning_steps': 20, 'expand_further': True, 'set_all_need_to_1': False, 'set_all_gain_to_1': False, 'baseline_gain': 1e-10, 'EVM_thresh': 0, 'allow_loops': False, 'online_offline': 'online', 'remove_samestate': True, 'gamma': 0.9, 'alpha': 1, 'lambda_': 0, 'T_learning_rate': 0.9, 'action_policy': 'softmax', 'epsilon': 0.05, 'tau': 0.2, 'simulations': 50, 'episodes': 50, 'max_episode_steps': 100000.0}


In [ ]:
mdp = create_random_maze(9, 1, 0) #linear
args.episodes = 100
args.simulations = 200
args.set_all_need_to_1 = True
args.start_random = True
print(get_args_string(args))
list_data = []
for i in range(args.simulations):
    replay = Replay()
    saver = SimuData(replay)
    rat = Agent(mdp, args, saver)
    rat.learn(args, seed = i)
    list_data.append(saver)

0_0.9_softmax_False_1_1e-10_100_0.05_True_0.9_0_100000.0_online_True_softmax_20_True_True_False_True_200_True_0.2_True_
#### EPISODE 1 ####
TRAIN: 28
#### EPISODE 2 ####
TRAIN: 10
#### EPISODE 3 ####
TRAIN: 34
#### EPISODE 4 ####
TRAIN: 10
#### EPISODE 5 ####
TRAIN: 22
#### EPISODE 6 ####
TRAIN: 11
#### EPISODE 7 ####
TRAIN: 15
#### EPISODE 8 ####
TRAIN: 22
#### EPISODE 9 ####
TRAIN: 26
#### EPISODE 10 ####
TRAIN: 2
#### EPISODE 11 ####
TRAIN: 50
#### EPISODE 12 ####
TRAIN: 11
#### EPISODE 13 ####
TRAIN: 14
#### EPISODE 14 ####
TRAIN: 12
#### EPISODE 15 ####
TRAIN: 1
#### EPISODE 16 ####
TRAIN: 4
#### EPISODE 17 ####
TRAIN: 21
#### EPISODE 18 ####
TRAIN: 10
#### EPISODE 19 ####
TRAIN: 49
#### EPISODE 20 ####
TRAIN: 15
#### EPISODE 21 ####
TRAIN: 6
#### EPISODE 22 ####
TRAIN: 9
#### EPISODE 23 ####
TRAIN: 1
#### EPISODE 24 ####
TRAIN: 11
#### EPISODE 25 ####
TRAIN: 5
#### EPISODE 26 ####
TRAIN: 35
#### EPISODE 27 ####
TRAIN: 22
#### EPISODE 28 ####
TRAIN: 5
#### EPISODE 29 ####
TRAIN: 3

#### EPISODE 66 ####
TRAIN: 31
#### EPISODE 67 ####
TRAIN: 33
#### EPISODE 68 ####
TRAIN: 45
#### EPISODE 69 ####
TRAIN: 64
#### EPISODE 70 ####
TRAIN: 23
#### EPISODE 71 ####
TRAIN: 3
#### EPISODE 72 ####
TRAIN: 1
#### EPISODE 73 ####
TRAIN: 48
#### EPISODE 74 ####
TRAIN: 34
#### EPISODE 75 ####
TRAIN: 14
#### EPISODE 76 ####
TRAIN: 38
#### EPISODE 77 ####
TRAIN: 22
#### EPISODE 78 ####
TRAIN: 8
#### EPISODE 79 ####
TRAIN: 2
#### EPISODE 80 ####
TRAIN: 5
#### EPISODE 81 ####
TRAIN: 18
#### EPISODE 82 ####
TRAIN: 56
#### EPISODE 83 ####
TRAIN: 16
#### EPISODE 84 ####
TRAIN: 11
#### EPISODE 85 ####
TRAIN: 11
#### EPISODE 86 ####
TRAIN: 4
#### EPISODE 87 ####
TRAIN: 4
#### EPISODE 88 ####
TRAIN: 30
#### EPISODE 89 ####
TRAIN: 7
#### EPISODE 90 ####
TRAIN: 1
#### EPISODE 91 ####
TRAIN: 1
#### EPISODE 92 ####
TRAIN: 7
#### EPISODE 93 ####
TRAIN: 40
#### EPISODE 94 ####
TRAIN: 31
#### EPISODE 95 ####
TRAIN: 7
#### EPISODE 96 ####
TRAIN: 11
#### EPISODE 97 ####
TRAIN: 20
#### EPISODE 98 ####

#### EPISODE 35 ####
TRAIN: 21
#### EPISODE 36 ####
TRAIN: 37
#### EPISODE 37 ####
TRAIN: 41
#### EPISODE 38 ####
TRAIN: 1
#### EPISODE 39 ####
TRAIN: 30
#### EPISODE 40 ####
TRAIN: 2
#### EPISODE 41 ####
TRAIN: 13
#### EPISODE 42 ####
TRAIN: 44
#### EPISODE 43 ####
TRAIN: 12
#### EPISODE 44 ####
TRAIN: 13
#### EPISODE 45 ####
TRAIN: 12
#### EPISODE 46 ####
TRAIN: 9
#### EPISODE 47 ####
TRAIN: 11
#### EPISODE 48 ####
TRAIN: 8
#### EPISODE 49 ####
TRAIN: 2
#### EPISODE 50 ####
TRAIN: 16
#### EPISODE 51 ####
TRAIN: 13
#### EPISODE 52 ####
TRAIN: 4
#### EPISODE 53 ####
TRAIN: 70
#### EPISODE 54 ####
TRAIN: 35
#### EPISODE 55 ####
TRAIN: 12
#### EPISODE 56 ####
TRAIN: 9
#### EPISODE 57 ####
TRAIN: 31
#### EPISODE 58 ####
TRAIN: 33
#### EPISODE 59 ####
TRAIN: 37
#### EPISODE 60 ####
TRAIN: 32
#### EPISODE 61 ####
TRAIN: 1
#### EPISODE 62 ####
TRAIN: 8
#### EPISODE 63 ####
TRAIN: 47
#### EPISODE 64 ####
TRAIN: 5
#### EPISODE 65 ####
TRAIN: 5
#### EPISODE 66 ####
TRAIN: 9
#### EPISODE 67 ####

#### EPISODE 4 ####
TRAIN: 2
#### EPISODE 5 ####
TRAIN: 21
#### EPISODE 6 ####
TRAIN: 26
#### EPISODE 7 ####
TRAIN: 36
#### EPISODE 8 ####
TRAIN: 16
#### EPISODE 9 ####
TRAIN: 13
#### EPISODE 10 ####
TRAIN: 21
#### EPISODE 11 ####
TRAIN: 10
#### EPISODE 12 ####
TRAIN: 18
#### EPISODE 13 ####
TRAIN: 38
#### EPISODE 14 ####
TRAIN: 23
#### EPISODE 15 ####
TRAIN: 9
#### EPISODE 16 ####
TRAIN: 25
#### EPISODE 17 ####
TRAIN: 33
#### EPISODE 18 ####
TRAIN: 17
#### EPISODE 19 ####
TRAIN: 5
#### EPISODE 20 ####
TRAIN: 2
#### EPISODE 21 ####
TRAIN: 10
#### EPISODE 22 ####
TRAIN: 12
#### EPISODE 23 ####
TRAIN: 39
#### EPISODE 24 ####
TRAIN: 28
#### EPISODE 25 ####
TRAIN: 16
#### EPISODE 26 ####
TRAIN: 13
#### EPISODE 27 ####
TRAIN: 15
#### EPISODE 28 ####
TRAIN: 9
#### EPISODE 29 ####
TRAIN: 14
#### EPISODE 30 ####
TRAIN: 32
#### EPISODE 31 ####
TRAIN: 39
#### EPISODE 32 ####
TRAIN: 25
#### EPISODE 33 ####
TRAIN: 19
#### EPISODE 34 ####
TRAIN: 22
#### EPISODE 35 ####
TRAIN: 36
#### EPISODE 36 ###

#### EPISODE 72 ####
TRAIN: 12
#### EPISODE 73 ####
TRAIN: 8
#### EPISODE 74 ####
TRAIN: 12
#### EPISODE 75 ####
TRAIN: 37
#### EPISODE 76 ####
TRAIN: 2
#### EPISODE 77 ####
TRAIN: 4
#### EPISODE 78 ####
TRAIN: 18
#### EPISODE 79 ####
TRAIN: 12
#### EPISODE 80 ####
TRAIN: 27
#### EPISODE 81 ####
TRAIN: 29
#### EPISODE 82 ####
TRAIN: 15
#### EPISODE 83 ####
TRAIN: 4
#### EPISODE 84 ####
TRAIN: 5
#### EPISODE 85 ####
TRAIN: 13
#### EPISODE 86 ####
TRAIN: 43
#### EPISODE 87 ####
TRAIN: 2
#### EPISODE 88 ####
TRAIN: 12
#### EPISODE 89 ####
TRAIN: 1
#### EPISODE 90 ####
TRAIN: 1
#### EPISODE 91 ####
TRAIN: 50
#### EPISODE 92 ####
TRAIN: 8
#### EPISODE 93 ####
TRAIN: 23
#### EPISODE 94 ####
TRAIN: 3
#### EPISODE 95 ####
TRAIN: 22
#### EPISODE 96 ####
TRAIN: 16
#### EPISODE 97 ####
TRAIN: 72
#### EPISODE 98 ####
TRAIN: 18
#### EPISODE 99 ####
TRAIN: 6
#### EPISODE 100 ####
TRAIN: 40
#### EPISODE 1 ####
TRAIN: 87
#### EPISODE 2 ####
TRAIN: 1
#### EPISODE 3 ####
TRAIN: 10
#### EPISODE 4 ####
TR

#### EPISODE 41 ####
TRAIN: 8
#### EPISODE 42 ####
TRAIN: 18
#### EPISODE 43 ####
TRAIN: 13
#### EPISODE 44 ####
TRAIN: 16
#### EPISODE 45 ####
TRAIN: 10
#### EPISODE 46 ####
TRAIN: 8
#### EPISODE 47 ####
TRAIN: 5
#### EPISODE 48 ####
TRAIN: 60
#### EPISODE 49 ####
TRAIN: 1
#### EPISODE 50 ####
TRAIN: 50
#### EPISODE 51 ####
TRAIN: 60
#### EPISODE 52 ####
TRAIN: 14
#### EPISODE 53 ####
TRAIN: 14
#### EPISODE 54 ####
TRAIN: 4
#### EPISODE 55 ####
TRAIN: 11
#### EPISODE 56 ####
TRAIN: 3
#### EPISODE 57 ####
TRAIN: 38
#### EPISODE 58 ####
TRAIN: 8
#### EPISODE 59 ####
TRAIN: 4
#### EPISODE 60 ####
TRAIN: 7
#### EPISODE 61 ####
TRAIN: 74
#### EPISODE 62 ####
TRAIN: 6
#### EPISODE 63 ####
TRAIN: 6
#### EPISODE 64 ####
TRAIN: 18
#### EPISODE 65 ####
TRAIN: 4
#### EPISODE 66 ####
TRAIN: 22
#### EPISODE 67 ####
TRAIN: 35
#### EPISODE 68 ####
TRAIN: 19
#### EPISODE 69 ####
TRAIN: 26
#### EPISODE 70 ####
TRAIN: 7
#### EPISODE 71 ####
TRAIN: 7
#### EPISODE 72 ####
TRAIN: 26
#### EPISODE 73 ####
T

#### EPISODE 10 ####
TRAIN: 10
#### EPISODE 11 ####
TRAIN: 30
#### EPISODE 12 ####
TRAIN: 43
#### EPISODE 13 ####
TRAIN: 25
#### EPISODE 14 ####
TRAIN: 53
#### EPISODE 15 ####
TRAIN: 10
#### EPISODE 16 ####
TRAIN: 9
#### EPISODE 17 ####
TRAIN: 15
#### EPISODE 18 ####
TRAIN: 44
#### EPISODE 19 ####
TRAIN: 1
#### EPISODE 20 ####
TRAIN: 24
#### EPISODE 21 ####
TRAIN: 4
#### EPISODE 22 ####
TRAIN: 2
#### EPISODE 23 ####
TRAIN: 16
#### EPISODE 24 ####
TRAIN: 17
#### EPISODE 25 ####
TRAIN: 16
#### EPISODE 26 ####
TRAIN: 44
#### EPISODE 27 ####
TRAIN: 12
#### EPISODE 28 ####
TRAIN: 7
#### EPISODE 29 ####
TRAIN: 17
#### EPISODE 30 ####
TRAIN: 12
#### EPISODE 31 ####
TRAIN: 44
#### EPISODE 32 ####
TRAIN: 3
#### EPISODE 33 ####
TRAIN: 8
#### EPISODE 34 ####
TRAIN: 2
#### EPISODE 35 ####
TRAIN: 23
#### EPISODE 36 ####
TRAIN: 17
#### EPISODE 37 ####
TRAIN: 2
#### EPISODE 38 ####
TRAIN: 2
#### EPISODE 39 ####
TRAIN: 54
#### EPISODE 40 ####
TRAIN: 19
#### EPISODE 41 ####
TRAIN: 15
#### EPISODE 42 ##

#### EPISODE 79 ####
TRAIN: 12
#### EPISODE 80 ####
TRAIN: 13
#### EPISODE 81 ####
TRAIN: 36
#### EPISODE 82 ####
TRAIN: 40
#### EPISODE 83 ####
TRAIN: 14
#### EPISODE 84 ####
TRAIN: 25
#### EPISODE 85 ####
TRAIN: 12
#### EPISODE 86 ####
TRAIN: 12
#### EPISODE 87 ####
TRAIN: 25
#### EPISODE 88 ####
TRAIN: 19
#### EPISODE 89 ####
TRAIN: 45
#### EPISODE 90 ####
TRAIN: 23
#### EPISODE 91 ####
TRAIN: 4
#### EPISODE 92 ####
TRAIN: 27
#### EPISODE 93 ####
TRAIN: 2
#### EPISODE 94 ####
TRAIN: 14
#### EPISODE 95 ####
TRAIN: 8
#### EPISODE 96 ####
TRAIN: 46
#### EPISODE 97 ####
TRAIN: 35
#### EPISODE 98 ####
TRAIN: 8
#### EPISODE 99 ####
TRAIN: 3
#### EPISODE 100 ####
TRAIN: 30
#### EPISODE 1 ####
TRAIN: 144
#### EPISODE 2 ####
TRAIN: 2
#### EPISODE 3 ####
TRAIN: 1
#### EPISODE 4 ####
TRAIN: 22
#### EPISODE 5 ####
TRAIN: 9
#### EPISODE 6 ####
TRAIN: 28
#### EPISODE 7 ####
TRAIN: 3
#### EPISODE 8 ####
TRAIN: 11
#### EPISODE 9 ####
TRAIN: 7
#### EPISODE 10 ####
TRAIN: 8
#### EPISODE 11 ####
TRAIN

#### EPISODE 47 ####
TRAIN: 37
#### EPISODE 48 ####
TRAIN: 13
#### EPISODE 49 ####
TRAIN: 24
#### EPISODE 50 ####
TRAIN: 28
#### EPISODE 51 ####
TRAIN: 39
#### EPISODE 52 ####
TRAIN: 18
#### EPISODE 53 ####
TRAIN: 13
#### EPISODE 54 ####
TRAIN: 57
#### EPISODE 55 ####
TRAIN: 2
#### EPISODE 56 ####
TRAIN: 26
#### EPISODE 57 ####
TRAIN: 12
#### EPISODE 58 ####
TRAIN: 2
#### EPISODE 59 ####
TRAIN: 2
#### EPISODE 60 ####
TRAIN: 54
#### EPISODE 61 ####
TRAIN: 1
#### EPISODE 62 ####
TRAIN: 1
#### EPISODE 63 ####
TRAIN: 11
#### EPISODE 64 ####
TRAIN: 2
#### EPISODE 65 ####
TRAIN: 2
#### EPISODE 66 ####
TRAIN: 16
#### EPISODE 67 ####
TRAIN: 11
#### EPISODE 68 ####
TRAIN: 33
#### EPISODE 69 ####
TRAIN: 33
#### EPISODE 70 ####
TRAIN: 9
#### EPISODE 71 ####
TRAIN: 1
#### EPISODE 72 ####
TRAIN: 30
#### EPISODE 73 ####
TRAIN: 42
#### EPISODE 74 ####
TRAIN: 12
#### EPISODE 75 ####
TRAIN: 20
#### EPISODE 76 ####
TRAIN: 1
#### EPISODE 77 ####
TRAIN: 19
#### EPISODE 78 ####
TRAIN: 49
#### EPISODE 79 ##

In [23]:
### ANALYSIS ###

min_num_cells = 5
min_frac_cells = 0
forward_count = np.zeros((len(list_data), mdp.nb_states))
reverse_count = np.zeros((len(list_data), mdp.nb_states))
next_state = np.full((mdp.nb_states, 4), np.NaN)

In [25]:

for s in range(mdp.nb_states):
    for a in range(mdp.action_space.size):
        mdp.reset()
        mdp.current_state = s
        s_next, _, _, _ = mdp.step(a)
        next_state[s, a] = s_next
print(next_state)

[[ 0.  1.  5.  0.]
 [ 0.  2.  6.  1.]
 [ 1.  2.  2.  2.]
 [ 3.  4.  8.  3.]
 [ 3.  4.  4.  4.]
 [ 5.  6.  9.  0.]
 [ 5.  6. 10.  1.]
 [ 7.  8. 12.  7.]
 [ 7.  8. 13.  3.]
 [ 9. 10. 15.  5.]
 [ 9. 11. 16.  6.]
 [10. 12. 17. 11.]
 [11. 13. 18.  7.]
 [12. 14. 13.  8.]
 [13. 14. 14. 14.]
 [15. 16. 19.  9.]
 [15. 17. 20. 10.]
 [16. 18. 21. 11.]
 [17. 18. 22. 12.]
 [19. 20. 25. 15.]
 [19. 21. 26. 16.]
 [20. 22. 27. 17.]
 [21. 23. 28. 18.]
 [22. 24. 23. 23.]
 [23. 24. 29. 24.]
 [25. 26. 30. 19.]
 [25. 27. 26. 20.]
 [26. 28. 31. 21.]
 [27. 28. 32. 22.]
 [29. 29. 33. 24.]
 [30. 30. 34. 25.]
 [31. 32. 31. 27.]
 [31. 32. 36. 28.]
 [33. 33. 33. 29.]
 [34. 35. 37. 30.]
 [34. 35. 38. 35.]
 [36. 36. 40. 32.]
 [37. 38. 37. 34.]
 [37. 39. 38. 35.]
 [38. 40. 39. 39.]
 [39. 41. 40. 36.]
 [40. 42. 41. 41.]
 [43. 43. 43. 43.]]


In [49]:

def get_candidate_events(data, mdp, min_frac_cells, min_num_cells):
    #Identify candidate replay events: timepoints in which the number of replayed states is greater than minFracCells,minNumCells
    candidate_events = []
    for idx, r_s in enumerate(data.replay.state):
        if len(r_s) >= max(mdp.nb_states * min_frac_cells , min_num_cells):
            candidate_events.append(idx)

    return candidate_events

In [ ]:
for k, data in enumerate(list_data):
    data.replay.state = np.array(data.replay.state, dtype = int).T
    data.replay.action = np.array(data.replay.action, dtype = int).T
    candidate_events = get_candidate_events(data, mdp, min_frac_cells, min_num_cells)
    lap_num = np.array(data.num_episodes) # episode number for each time point
    lap_num_events = lap_num[candidate_events] # episode number for each candidate event
    agent_pos = np.array(data.list_exp)[candidate_events]# agent position during each candidate event
    agent_pos = agent_pos[:,0]
    for e, evt in enumerate(candidate_events):
        event_state = np.array(data.replay.state[evt], dtype = int) # In a multi-step sequence, simData.replay.state has 1->2 in one row, 2->3 in another row, etc
        event_action = np.array(data.replay.action[evt], dtype = int) # In a multi-step sequence, simData.replay.action has the action taken at each step of the trajectory
        # Identify break points in this event, separating event into sequences
        event_dir = np.full(len(event_state)- 1, "")
        break_points = [0] # Save breakpoints that divide contiguous replay events

        for i, evt_state in enumerate(event_state[:-1]):
            # If state(i) and action(i) leads to state(i+1): FORWARD
            if next_state[event_state[i], event_action[i]] == event_state[i +1]:
                event_dir[i] = "F"

            # If state(i+1) and action(i+1) leads to state(i): REVERSE
            if next_state[event_state[i + 1], event_action[i + 1]] == event_state[i]:
                event_dir[i] = "R"
                
            if event_dir[i] == "": # If this transition was neither forward nor backward
                break_points.append(i) # Then, call this a breakpoint

            elif i > 0:
                if event_dir[i] != event_dir[i - 1]:
                    break_points.append(i)

            if (i + 1) == (len(event_state) - 1):
                break_points.append(i + 1) # Add a breakpoint after the last transition

        # Break this event into segments of sequential activity
        for j, b_pt in enumerate(break_points[:-1]):
            this_chunk = list(range(break_points[j] + 1, break_points[j + 1]))
            if (len(this_chunk) + 1) >= min_num_cells:
                # Extract information from this sequential event
                replay_dir = event_dir[this_chunk] # Direction of transition
                replay_state = event_state[this_chunk + [this_chunk[-1] + 1]] # start state
                replay_action = event_action[this_chunk + [this_chunk[-1] + 1]] # action

                if replay_dir[0] == "F":
                    forward_count[k, int(agent_pos[e])] += 1
                elif replay_dir[0] == "R":
                    reverse_count[k, int(agent_pos[e])] +=1

#
# Compute the number of significant events BEFORE (preplay) and AFTER (replay) an event (which could be larger than 1)
# PS: Notice that this is not a measure of the percent of episodes with a significant event (which would produce a smaller numbers)

preplay_forward = np.nansum(forward_count[:,: -1 ], axis=0) / args.episodes # goal state is always last
replay_forward = np.nansum(forward_count[:, -1], axis=0) / args.episodes
preplay_reverse = np.nansum(reverse_count[:,: -1 ],axis=0) / args.episodes # goal state is always last
replay_reverse = np.nansum(reverse_count[:, -1], axis=0) / args.episodes
print([np.nanmean(preplay_forward), np.nanmean(replay_forward), np.nanmean(preplay_reverse), np.nanmean(replay_reverse)])
fig = plt.figure()
ax = fig.add_axes([0,0,1,1])
lab = ["Pre-For", 'Repl-For', 'Pre-Back', 'Repl-Back']
to_plot = [np.nanmean(preplay_forward), np.nanmean(replay_forward), np.nanmean(preplay_reverse), np.nanmean(replay_reverse)]
ax.bar(lab,to_plot)
plt.show()
plt.savefig("results/Mattar/linear_mattar_fig_3_a_default.png")